import type { ZongceSession } from './session'

/** 开发调试用演示数据：保险学院 · 大三，覆盖 ok / pending_review / needs_evidence / external 四种状态 */
export function buildDemoSession(): ZongceSession {
  return {
    version: 1,
    college: '保险学院',
    packVersion: 'v0.2',
    packSourceDoc: '保险学院综测细则（2024年3月修订）',
    grade: '大三',
    evalYear: '2024–2025 学年',
    savedAt: new Date().toISOString(),
    moduleStatus: {
      德育: 'done',
      智育: 'done',
      体育: 'done',
      学术科研: 'done',
      组织管理: 'done',
      劳动实践: 'partial',
      美育: 'partial',
    },
    items: [
      {
        itemRef: 'deyu-q2',
        name: '参加校级以上主题教育讲座（含保险行业大讲堂）',
        module: '德育',
        score: 2,
        systemNode: '德育评价 → 学习态度 → 讲座与学术活动',
        routeTo: null,
        note: null,
        evidence: { suggested: '讲座签到记录', uploaded: true },
        status: 'ok',
        sourceQuote: '第 3 条：参加校级以上主题教育讲座、报告会，每次加 1 分，累计不超过 2 分。',
      },
      {
        itemRef: 'deyu-q5',
        name: '无偿献血（本学年）',
        module: '德育',
        score: [2, 4],
        systemNode: '德育评价 → 社会责任 → 志愿服务与公益',
        routeTo: null,
        note: '按献血证登记次数认定，等级由评议小组核定。',
        evidence: { suggested: '献血证', uploaded: false },
        status: 'pending_review',
        sourceQuote: '第 7 条：参加无偿献血，每次加 2–4 分，以献血证为准。',
      },
      {
        itemRef: 'zhiyu-q1',
        name: '大学英语六级（CET-6）通过',
        module: '智育',
        score: 4,
        systemNode: '智育评价 → 学习能力 → 外语水平',
        routeTo: null,
        note: null,
        evidence: { suggested: '成绩单截图', uploaded: true },
        status: 'ok',
        sourceQuote: '第 11 条：非英语专业学生通过 CET-6，加 4 分。',
      },
      {
        itemRef: 'tiyu-q2',
        name: '校级运动会个人项目前三名',
        module: '体育',
        score: 3,
        systemNode: '体育评价 → 体育竞赛 → 校级赛事获奖',
        routeTo: null,
        note: null,
        evidence: { suggested: '获奖证书或秩序册', uploaded: false },
        status: 'needs_evidence',
        sourceQuote: '第 15 条：校运会个人项目前三名，分别加 3 / 2.5 / 2 分。',
      },
      {
        itemRef: 'tiyu-q4',
        name: '体质健康测试等级：良',
        module: '体育',
        score: 6,
        systemNode: '体育评价 → 体质健康 → 体测成绩',
        routeTo: null,
        note: '系统自动带出体测等级，无需重复上传。',
        evidence: { suggested: null, uploaded: false },
        status: 'ok',
        sourceQuote: '第 16 条：体测等级为“良”，加 6 分；“优”加 8 分。',
      },
      {
        itemRef: 'keyan-q2',
        name: '大学生创新训练项目立项（自报国家级）',
        module: '学术科研',
        score: [6, 8],
        systemNode: '科研训练 → 大创项目 → 立项等级',
        routeTo: null,
        note: '手动定级：国家级 — 定级最终以评议小组认定为准。',
        evidence: { suggested: '立项通知书 / 公示名单', uploaded: true },
        status: 'pending_review',
        sourceQuote: '第 21 条：大创项目立项，校级 4 分、省部级 6 分、国家级 8 分。',
      },
      {
        itemRef: 'keyan-q5',
        name: '学科竞赛获奖（省部级三等奖）',
        module: '学术科研',
        score: 5,
        systemNode: '科研训练 → 学科竞赛 → 获奖登记',
        routeTo: null,
        note: null,
        evidence: { suggested: '获奖证书', uploaded: false },
        status: 'needs_evidence',
        sourceQuote: '第 23 条：省部级学科竞赛三等奖，加 5 分。',
      },
      {
        itemRef: 'zuzhi-q1',
        name: '担任班级班长满一学年（考核合格）',
        module: '组织管理',
        score: 3,
        systemNode: '组织管理 → 学生干部 → 班级职务',
        routeTo: null,
        note: null,
        evidence: { suggested: '辅导员开具的任职证明', uploaded: true },
        status: 'ok',
        sourceQuote: '第 27 条：班长、团支书任职满一学年且考核合格，加 3 分。',
      },
      {
        itemRef: 'laodong-q3',
        name: '志愿服务 12 小时（院内组织）',
        module: '劳动实践',
        score: 6,
        systemNode: null,
        routeTo: '其他',
        note: '12 小时 · 院内志愿活动，按 0.5 分/小时折算 6 分。',
        evidence: { suggested: '志愿时长记录（志愿北京截图）', uploaded: true },
        status: 'ok',
        sourceQuote: '第 31 条：院内志愿服务按 0.5 分/小时计，上限 6 分；系统无对应栏位时计入“其他”。',
      },
      {
        itemRef: 'laodong-q6',
        name: '宿舍卫生评比优秀（连续两学期）',
        module: '劳动实践',
        score: 1,
        systemNode: '劳动实践 → 宿舍建设 → 卫生评比',
        routeTo: null,
        note: null,
        evidence: { suggested: '宿管公示截图', uploaded: false },
        status: 'ok',
        sourceQuote: '第 33 条：宿舍卫生评比连续两学期优秀，加 1 分。',
      },
      {
        itemRef: 'meiyu-q1',
        name: '校艺术团正式成员满一年',
        module: '美育',
        score: 2,
        systemNode: null,
        routeTo: '其他',
        note: '本项由校团委端口统一认定，系统栏位开放后手动填入。',
        evidence: { suggested: '艺术团在团证明', uploaded: false },
        status: 'external',
        sourceQuote: '第 37 条：校艺术团正式成员满一年，加 2 分。',
      },
      {
        itemRef: 'meiyu-q4',
        name: '迎新晚会 / 毕业晚会参演',
        module: '美育',
        score: [1, 2],
        systemNode: '美育评价 → 文艺活动 → 校级演出',
        routeTo: null,
        note: '按参演节目数量与角色在区间内定分。',
        evidence: { suggested: '节目单 / 演出照片', uploaded: false },
        status: 'pending_review',
        sourceQuote: '第 39 条：参加校级文艺晚会演出，每次加 1–2 分。',
      },
    ],
    totals: {
      perModule: {
        德育: 5,
        智育: 4,
        体育: 9,
        学术科研: 12,
        组织管理: 3,
        劳动实践: 7,
        美育: 3.5,
      },
      note: '参考合计，非最终得分；区间分与评议项以评议小组认定为准。',
    },
  }
}
